CREATE DATABASE taskmanagement;
use taskmanagement;
CREATE TABLE users (
	user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	pw_hash VARCHAR(255) NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	active TINYINT(1) NOT NULL DEFAULT 1,
	admin TINYINT(1) NOT NULL DEFAULT 0
);
CREATE TABLE tasks (
	task_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL,
	title VARCHAR(50) NOT NULL,
	description TEXT,
	status ENUM('not_started', 'in_progress', 'completed') NOT NULL DEFAULT 'not_started',
	estimated_hr INT UNSIGNED,
	due DATE,
	priority INT,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	censor TINYINT(1) NOT NULL DEFAULT 0,
	overwrite INT UNSIGNED DEFAULT NULL,

	CONSTRAINT fk_user_id FOREIGN KEY (user_id)
		REFERENCES users(user_id)
		ON DELETE CASCADE,

	CONSTRAINT fk_task_overwrite FOREIGN KEY (overwrite)
		REFERENCES tasks(task_id)
		ON DELETE SET NULL
);
